
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect everything to index (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
